---
  - name: setup web server and add first web page
    hosts: webserver1
    tasks:
      - name: install httpd packages
        yum:
          name: httpd
          state: latest

      - name: start and enable httpd service
        service:
          name: httpd
          enabled: true
          state: started
      - name: create first web page for index.html
        copy:
          content: 'name: kai \nID: G080A002\n'
          dest: /var/www/html/index.html

      - name: add http port to firewalld
        firewalld:
          service: http
          state: enabled
          permanent: true
          immediate: true
