---
  - name: check user is OK or FAIL
    hosts: webserver1
    tasks:
      - name: use id to check joe man
        shell: "id joe && echo OK || echo FAIL"
        register: myoutput
        changed_when: "'FAIL' in myoutput.stdout"
        notify: create joe

      - name: show message
        debug:
          msg: "{{ myoutput }}"

    handlers:
      - name: create joe
        user:
          user: joe
          state: present

