---
  - name: create user facts
    hosts: webserver1
    vars:
      - src_file: myweb.fact
      - dest_dir: /etc/ansible/facts.d/
    tasks:
      - name: create dest_dir
        file: 
          path: "{{ dest_dir }}"
          mode: 0775
          state: directory
      
      - name: copy src_file to webserver1
        copy:
          src: "{{ src_file }}"
          dest: "{{ dest_dir }}"
          
