---
  - name: create user and group
    hosts: webserver1
    vars:
      myuser:
        - exuser1
        - exuser2
        - exuser3
        - exuser4

    tasks:
      - name: 1st task create group
        group:
          name: exgroup
          state: present
          gid: 3106

      - name: 2nd task create users
        loop: "{{ myuser }}"
        user:
          name: "{{ item }}"
          groups: exgroup
          state: present
          append: true

      - name: 3th task use id check 
        loop: "{{ myuser }}"
        command: id "{{ item }}"
        register: myoutput
      
      - name: 4th task show output
        debug:
          msg: show id output is "{{ item.stdout_lines }}"
        loop: "{{ myoutput['results'] }}"
