---
  - name: do not use loop to show service
    hosts: webserver1
    tasks:
      - name: check "{{ item }}" service status
        command:
          cmd: systemctl is-active "{{ item }}"
        loop:
          - httpd
          - sshd
          - tuned
        register: myoutput
      - name: show output
        debug:
          #var: myoutput
          #msg: output is "{{ item.stdout }}"
          msg: output is aaaaaaaaaaaaaaaaaaaa "{{ item.stdout }}"
        loop: "{{ myoutput['results'] }}"
