---
  - name: add 172.16.200.254 to webserver1
    hosts: webserver1
    tasks:
    - name: type 172.16.200.254 bigdata to /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: 172.16.200.254 bigdata
    - name: Ensure the default Apache port is 8080
      lineinfile:
        path: /root/test.txt
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 8080
