---
  - name: setup servers package
    hosts:
      - website
      - devel
      - mylab
    tasks:
      - name: install packages "{{ pkg }}" for different server
        yum:
          name: "{{ pkg }}"
          state: latest
