---
  - name: add user for managed hosts
    hosts: webserver1
    vars:
      username: alex
      password: $6$WmbRmtWfLY3Mt6zW$aiGERNiUNXxtGpvoTncdbspdmkVvM3NCMk18rSG3I64liJ2H29fHjTICejTDTFTjJD.6kDl8b2u1mkd1Hbg270
      uid: 3102
    tasks:
    - name: use user module to create user "{{username}}"
      user:
        name: "{{ username }}"
        uid: "{{uid}}"
        password: "{{password}}"
