---
  - name: restart httpd when configure changed
    hosts: webserver1
    force_handlers: true
    tasks: 
      - name: install httpd
        yum:
          name: httpd
          state: present
      
      - name: upload configure file
        copy:
          src: check.conf
          dest: /etc/httpd/conf.d/check.conf

        notify:
          - restart httpd
      - name: failure install pkg
        yum:
          name: hehehaha
          state: present
    
    handlers:
      - name: restart httpd
        service:
          name: httpd
          state: restarted

